apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
   name: {{ include "w7panel-metrics.fullname" . }}-hami-31993
   labels:
         {{- include "w7panel-metrics.labels" . | nindent 4 }}
spec:
    endpoints:
        -
            # bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
            port: monitor
            scheme: http
            # tlsConfig:
            #     caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            #     serverName: kubernetes
    jobLabel: component
    namespaceSelector:
        matchNames:
            - default
    selector:
        matchLabels:
            app.kubernetes.io/component: hami-scheduler