{{- $storageClassName := default .Values.storage.storageClassName .Values.victoriaLogs.storage.storageClassName }}
{{- if .Values.victoriaLogs.enabled }}
apiVersion: operator.victoriametrics.com/v1
kind: VLSingle
metadata:
   name: {{ include "w7panel-metrics.fullname" . }}
   labels:
         {{- include "w7panel-metrics.labels" . | nindent 4 }}
spec:
    retentionPeriod: {{ .Values.victoriaLogs.retentionPeriod | quote }}
    removePvcAfterDelete: {{ .Values.victoriaLogs.removePvcAfterDelete }}
    storage:
{{ if $storageClassName }}
        storageClassName: {{ $storageClassName | quote }}
{{ end }}
        accessModes:
            {{- range .Values.victoriaLogs.storage.accessModes }}
            - {{ . | quote }}
            {{- end }}
        resources:
            requests:
                storage: {{ .Values.victoriaLogs.storage.size | quote }}
{{- end }}
